# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yam' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yam
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  target 'yam-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yamTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'yam-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yam-tvOS

  target 'yam-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
